/**
 * mcp-reference-doc.test.ts — regression guard for docs/MCP-TOOL-REFERENCE.md.
 *
 * The doc is generated by scripts/generate-mcp-reference.ts. If a tool is added
 * to mcp-server.ts (or tools/deliberate.ts) without re-running
 * `npm run docs:mcp-ref`, this test fails with a useful list of missing
 * sections.
 */
import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const DOC = path.join(REPO_ROOT, "docs", "MCP-TOOL-REFERENCE.md");
const MCP_SERVER_TS = path.join(REPO_ROOT, "packages", "mcp", "src", "mcp-server.ts");
const DELIBERATE_TS = path.join(REPO_ROOT, "packages", "mcp", "src", "tools", "deliberate.ts");

function extractRegisteredTools(): Set<string> {
  const re = /name:\s*"(zana_[a-zA-Z0-9_]+)"/g;
  const set = new Set<string>();
  for (const file of [MCP_SERVER_TS, DELIBERATE_TS]) {
    const src = fs.readFileSync(file, "utf8");
    let m: RegExpExecArray | null;
    while ((m = re.exec(src))) set.add(m[1]);
    re.lastIndex = 0;
  }
  return set;
}

function extractDocSections(): Set<string> {
  const re = /^##\s+(zana_[a-zA-Z0-9_]+)\s*$/gm;
  const src = fs.readFileSync(DOC, "utf8");
  const set = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = re.exec(src))) set.add(m[1]);
  return set;
}

describe("MCP-TOOL-REFERENCE.md", () => {
  it("documents every registered MCP tool", () => {
    const registered = extractRegisteredTools();
    const documented = extractDocSections();

    const missing = [...registered].filter((t) => !documented.has(t)).sort();
    const orphans = [...documented].filter((t) => !registered.has(t)).sort();

    expect(
      missing,
      `Tools registered but missing from MCP-TOOL-REFERENCE.md (run \`npm run docs:mcp-ref\`):\n  ${missing.join("\n  ")}`,
    ).toEqual([]);

    expect(
      orphans,
      `Doc sections for tools no longer registered (regenerate the doc):\n  ${orphans.join("\n  ")}`,
    ).toEqual([]);
  });

  it("section count matches registered tool count", () => {
    expect(extractDocSections().size).toBe(extractRegisteredTools().size);
  });
});
